JobFairManager/Controllers/JobController.cs
using JobFairManager.Data;
using JobFairManager.Dto;
using JobFairManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Web;

namespace JobFairManager.Controllers
{
    public class JobController : Controller
    {
        private readonly JobFairDbContext _context;

        public JobController(JobFairDbContext context)
        {
            _context = context;
        }

        
        public IActionResult Details(int id)
        {
            var article = _context.Jobs.Where(m => m.JobId == id).FirstOrDefault();

            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Jobs entity)
        {
            if (!string.IsNullOrWhiteSpace(entity.JobTitle) && !string.IsNullOrWhiteSpace(entity.JobDescription))
            {
                entity.JobTitle = HttpUtility.HtmlEncode(entity.JobTitle);
                entity.JobDescription = HttpUtility.HtmlEncode(entity.JobDescription);
                entity.Requirements = HttpUtility.HtmlEncode(entity.Requirements);
                entity.CreatedDate = DateTime.Now;

                _context.Jobs.Add(entity);
                _context.SaveChanges();
                return Json(new { success = true });
            }

            return Json(new { success = false });
        }


        // 招聘列表页面
        public IActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            var jobs = _context.Jobs.AsQueryable();

            // 搜索功能
            if (!string.IsNullOrWhiteSpace(searchString))
            {
                jobs = jobs.Where(j => j.JobTitle.Contains(searchString));
            }

            // 分页功能
            var paginatedJobs = jobs
                                .OrderByDescending(j => j.CreatedDate) // 按发布日期排序
                                .Skip((page - 1) * pageSize)
                                .Take(pageSize)
                                .ToList();

            // 计算总页数
            var totalJobs = jobs.Count();
            var totalPages = (int)Math.Ceiling(totalJobs / (double)pageSize);

            // 传递分页相关数据到前端
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.SearchString = searchString;

            return View(paginatedJobs);
        }


        // 显示所有简历提交记录
        public IActionResult ResumeList()
        {
            List<ResumesDto> resumesDto = new List<ResumesDto>();
            var currentUser = HttpContext.Session.GetString("Username");
            if (currentUser == "admin")
            {
                var resumes = _context.Resumes
                               .ToList();
                var userids = resumes.Select(m => m.UserId).ToArray();
                var jobids = resumes.Select(m => m.JobId).ToArray();
                var users = _context.Users.Where(m => userids.Contains(m.Id)).ToList();
                var jobs = _context.Jobs.Where(m => jobids.Contains(m.JobId)).ToList();

               
                foreach (var item in resumes)
                {
                    ResumesDto dto = new ResumesDto();
                    dto.UserName = users.FirstOrDefault(m => m.Id == item.UserId).Username;
                    dto.JobName = jobs.FirstOrDefault(m => m.JobId == item.JobId).JobTitle;
                    dto.ResumesId = item.ResumeId;
                    dto.FilePath = item.FilePath;
                    dto.SubmissionDate = item.SubmissionDate;
                    resumesDto.Add(dto);
                }
                return View(resumesDto);
            }
            return View(resumesDto);
           
        }

        
    }
}

JobFairManager/Controllers/UserController.cs
using JobFairManager.Data;
using JobFairManager.Dto;
using JobFairManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;
using System.Web;

namespace JobFairManager.Controllers
{
    public class UserController : Controller
    {
        private readonly JobFairDbContext context;

        public UserController(JobFairDbContext context)
        {
            this.context = context;
        }
        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public JsonResult Login([FromBody] LoginDto dto)
        {
            dto.username = HttpUtility.HtmlEncode(dto.username);
            dto.password = HttpUtility.HtmlEncode(dto.password);
            var user = this.context.Users.SingleOrDefault(u => u.Username == dto.username);

            if (user != null && user.PasswordHash == HashPassword(dto.password, user.Salt))
            {
                HttpContext.Session.SetString("Username", user.Username);
                HttpContext.Session.SetString("UserId", user.Id.ToString());

                // 返回登录成功的消息
                return Json(new { success = true, message = "Login successful!" });
            }
            //如果登录失败，返回失败的消息
            return Json(new { success = false, message = "Invalid username or password." });
        }




        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Register([FromBody] LoginDto dto)
        {
            if (dto == null)
            {
                return Json(new { success = false, message = "Invalid data." });
            }
            var isUser = this.context.Users.Any(u => u.Username == dto.username);
            if (isUser)
            {
                return Json(new { success = false, message = "Username already exists." });
            }
            User user = new User
            {
                Username = HttpUtility.HtmlEncode(dto.username),
                PasswordHash = HttpUtility.HtmlEncode(dto.password)
            };

            if (ModelState.IsValid)
            {
                user.Salt = GenerateSalt();
                user.PasswordHash = HashPassword(dto.password, user.Salt);

                this.context.Users.Add(user);
                this.context.SaveChanges();

                return Json(new { success = true, message = "Registration successful!" });
            }

            return Json(new { success = false, message = "Registration failed." });
        }




        public IActionResult Logout()
        {
            HttpContext.Session.Remove("Username");
            return RedirectToAction("Index", "Home");
        }
        private string GenerateSalt()
        {
            var rng = new RNGCryptoServiceProvider();
            var buffer = new byte[16];
            rng.GetBytes(buffer);
            return Convert.ToBase64String(buffer);
        }
        private string HashPassword(string password, string salt)
        {
            var sha256 = SHA256.Create();
            var saltedPassword = Encoding.UTF8.GetBytes(password + salt);
            return Convert.ToBase64String(sha256.ComputeHash(saltedPassword));
        }
    }
}

JobFairManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeIndex</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Hospital Recruitment</a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        @if (Context.Session.GetString("Username") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Login", "User")">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Register", "User")">Register</a>
                            </li>
                        }
                        else
                        {
                            if (Context.Session.GetString("Username") == "admin")
                            {
                                <li class="nav-item">
                                    <span class="nav-link">welcome, @Context.Session.GetString("Username")</span>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Index", "Job")">Recruitment List</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("ResumeList", "Job")">Resume List</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Logout", "User")">Loginout</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Create", "Job")">Post Recruitment</a>
                                </li>
                            }else
                            {
                                <li class="nav-item">
                                    <span class="nav-link">welcome, @Context.Session.GetString("Username")</span>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Index", "Job")">Recruitment List</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Logout", "User")">Loginout</a>
                                </li>
                            }
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>